### ISSUE TITLE
Домашка №4, HTML + CSS = make them work

### ISSUE THREAD

**Issue by tiny-kottan** [jalaz/kottans-homework#5]
Задание: сверсать по [wireframe](http://en.wikipedia.org/wiki/Website_wireframe) https://moqups.com/sudodoki/KljcOP8V. Из особенностей: в левом верхнем углу - переключалка между 3мя видами одной и той же странице. В задании могут пригодиться [media query](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries), о которых так приятно читать самому. Вопросы не стесняйтесь задавать в общий чат. :smile_cat:

**Comment by mayosh** [comment]
.copyright:before{
    content: "© "
}

Рекомендую воспользоваться http://www.evotech.net/blog/2007/08/css-javascript-character-entities/
и изменить контент на:
content: "\00A9 "
